Vak :Datalab II
Groep: 4B
Namen: 
Jacco van den Dobbelsteen(17100976)

## Eerst installeren we de nodige libraries en packets en lezen we de SQL database in

In [1]:
!pip install psycopg2-binary

Requirement already satisfied: psycopg2-binary in c:\users\jvddo\anaconda3\lib\site-packages (2.9.5)

In [2]:
!pip install pyodbc

Requirement already satisfied: pyodbc in c:\users\jvddo\anaconda3\lib\site-packages (4.0.32)

In [3]:
#Improts 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import sqlite3
import matplotlib.pyplot as plt

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list the files in the input directory

path = "database.sqlite"  #Insert path here
database = path

In [4]:
pd.set_option('display.max_columns', 200)

In [5]:
conn = sqlite3.connect(database)

tables = pd.read_sql("""SELECT *
                        FROM sqlite_master
                        WHERE type='table';""", conn)
tables

,type,name,tbl_name,rootpage,sql
0,table,sqlite_sequence,sqlite_sequence,4,"CREATE TABLE sqlite_sequence(name,seq)"
1,table,Player_Attributes,Player_Attributes,11,"CREATE TABLE ""Player_Attributes"" (\n\t`id`\tIN..."
2,table,Player,Player,14,CREATE TABLE `Player` (\n\t`id`\tINTEGER PRIMA...
3,table,Match,Match,18,CREATE TABLE `Match` (\n\t`id`\tINTEGER PRIMAR...
4,table,League,League,24,CREATE TABLE `League` (\n\t`id`\tINTEGER PRIMA...
5,table,Country,Country,26,CREATE TABLE `Country` (\n\t`id`\tINTEGER PRIM...
6,table,Team,Team,29,"CREATE TABLE ""Team"" (\n\t`id`\tINTEGER PRIMARY..."
7,table,Team_Attributes,Team_Attributes,2,CREATE TABLE `Team_Attributes` (\n\t`id`\tINTE...

Country = pd.read_sql("""SELECT *
                        FROM Country;""", conn)
Country

In [6]:
League = pd.read_sql("""SELECT *
                        FROM League;""", conn)
League

       id  country_id                      name
0       1           1    Belgium Jupiler League
1    1729        1729    England Premier League
2    4769        4769            France Ligue 1
3    7809        7809     Germany 1. Bundesliga
4   10257       10257             Italy Serie A
5   13274       13274    Netherlands Eredivisie
6   15722       15722        Poland Ekstraklasa
7   17642       17642  Portugal Liga ZON Sagres
8   19694       19694   Scotland Premier League
9   21518       21518           Spain LIGA BBVA
10  24558       24558  Switzerland Super League

In [ ]:
Match = pd.read_sql("""SELECT *
                        FROM Match;""", conn)
Match

In [ ]:
Player = pd.read_sql("""SELECT *
                        FROM Player;""", conn)
Player

In [ ]:
Player_A = pd.read_sql("""SELECT *
                        FROM Player_Attributes;""", conn)
Player_A

In [ ]:
Teams = pd.read_sql("""SELECT *
                        FROM Team;""", conn)
Teams

In [ ]:
Team_A = pd.read_sql("""SELECT *
                        FROM Team_Attributes""", conn)
Team_A

Beschrijf welke tabellen  beschikbaar zijn.
Er zijn een aantal tabellen in de dataset:

-Country: Een lijst met landen en bijbehorende id's van de clubs in het EK.

-League: Een lijst van alle competities in Europa met bijbehorende id's.

-Match: Een lijst met gegevens van wedstrijden uit seizoenen (2008-2016)

-Player: Een lijst met gegevens van spelers zoals hun id, geboortejaar, gewicht en lengte.

Player_Attributes: Een lijst met gegevens van spelers van wedstrijden zoals rating, penalties en tackles.

Team: Een lijst van teams uit de competities met bijbehorende id's en de afkorting van de naam.

Team_Attributes: Een lijst met attributen van teams van alle wedstrijden bij elkaar. Hierin staan gegevens over bv. snelheid en tactiek.

Beschrijf de data die je kunt vinden in iedere tabel.
Bepaal de volgende gegevens van jouw club:
team naam
team id
competitie id
competitie naam
De gegevens van alle wedstrijden die jouw club heeft gespeeld.

In [90]:
PSV = pd.read_sql("""SELECT p1.*, p2.id, p2.name,
                    p3.*
                    FROM Team AS p1
                    INNER JOIN League AS p2
                    INNER JOIN Match AS p3
                    WHERE team_api_id = '8640';""", conn)
PSV
df_PSV = pd.DataFrame(PSV)
#De team naam is PSV. de korte naam is ook PSV. De team id is 8640. PSV heeft in verscheidene competities gespeeld. De id's en namen van deze competities en de gegevens van alle wedstrijden staan in het dataframe hieronder. 
display(df_PSV)

KeyboardInterrupt

Gebruik functies en dataframes om het volgende te bepalen:

Maak een functie waarmee je per seizoen voor een gekozen club o.a. het volgende kunt bepalen:

Aantal wedstrijden in dat seizoen.
Aantal punten behaald in dat seizoen.
Gemiddeld aantal punten per wedstrijd.
Winst-, verlies- en gelijk percentage in uitwedstrijden en thuiswedstrijden.
Pas deze functie toe op een seizoen naar keuze en bepaal de ranglijst van dat seizoen.

In [10]:
df_Match = pd.DataFrame(Match)
df_Match

,id,country_id,league_id,season,stage,date,match_api_id,home_team_api_id,away_team_api_id,home_team_goal,away_team_goal,home_player_X1,home_player_X2,home_player_X3,home_player_X4,home_player_X5,home_player_X6,home_player_X7,home_player_X8,home_player_X9,home_player_X10,home_player_X11,away_player_X1,away_player_X2,away_player_X3,away_player_X4,away_player_X5,away_player_X6,away_player_X7,away_player_X8,away_player_X9,away_player_X10,away_player_X11,home_player_Y1,home_player_Y2,home_player_Y3,home_player_Y4,home_player_Y5,home_player_Y6,home_player_Y7,home_player_Y8,home_player_Y9,home_player_Y10,home_player_Y11,away_player_Y1,away_player_Y2,away_player_Y3,away_player_Y4,away_player_Y5,away_player_Y6,away_player_Y7,away_player_Y8,away_player_Y9,away_player_Y10,away_player_Y11,home_player_1,home_player_2,home_player_3,home_player_4,home_player_5,home_player_6,home_player_7,home_player_8,home_player_9,home_player_10,home_player_11,away_player_1,away_player_2,away_player_3,away_player_4,away_player_5,away_player_6,away_player_7,away_player_8,away_player_9,away_player_10,away_player_11,goal,shoton,shotoff,foulcommit,card,cross,corner,possession,B365H,B365D,B365A,BWH,BWD,BWA,IWH,IWD,IWA,LBH,LBD,LBA,PSH,PSD,PSA,WHH,WHD,WHA,SJH,SJD,SJA,VCH,VCD,VCA,GBH,GBD,GBA,BSH,BSD,BSA
0,1,1,1,2008/2009,1,2008-08-17 00:00:00,492473,9987,9993,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,None,None,None,None,None,1.73,3.40,5.00,1.75,3.35,4.20,1.85,3.2,3.5,1.80,3.3,3.75,NaN,NaN,NaN,1.70,3.30,4.33,1.90,3.3,4.00,1.65,3.40,4.50,1.78,3.25,4.00,1.73,3.40,4.20
1,2,1,1,2008/2009,1,2008-08-16 00:00:00,492474,10000,9994,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,None,None,None,None,None,1.95,3.20,3.60,1.80,3.30,3.95,1.90,3.2,3.5,1.90,3.2,3.50,NaN,NaN,NaN,1.83,3.30,3.60,1.95,3.3,3.80,2.00,3.25,3.25,1.85,3.25,3.75,1.91,3.25,3.60
2,3,1,1,2008/2009,1,2008-08-16 00:00:00,492475,9984,8635,0,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,None,None,None,None,None,2.38,3.30,2.75,2.40,3.30,2.55,2.60,3.1,2.3,2.50,3.2,2.50,NaN,NaN,NaN,2.50,3.25,2.40,2.63,3.3,2.50,2.35,3.25,2.65,2.50,3.20,2.50,2.30,3.20,2.75
3,4,1,1,2008/2009,1,2008-08-17 00:00:00,492476,9991,9998,5,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,None,None,None,None,None,1.44,3.75,7.50,1.40,4.00,6.80,1.40,3.9,6.0,1.44,3.6,6.50,NaN,NaN,NaN,1.44,3.75,6.00,1.44,4.0,7.50,1.45,3.75,6.50,1.50,3.75,5.50,1.44,3.75,6.50
4,5,1,1,2008/2009,1,2008-08-16 00:00:00,492477,7947,9985,1,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,None,None,None,None,None,5.00,3.50,1.65,5.00,3.50,1.60,4.00,3.3,1.7,4.00,3.4,1.72,NaN,NaN,NaN,4.20,3.40,1.70,4.50,3.5,1.73,4.50,3.40,1.65,4.50,3.50,1.65,4.75,3.30,1.67
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25974,25975,24558,24558,2015/2016,9,2015-09-22 00:00:00,1992091,10190,10191,1,0,1.0,2.0,4.0,6.0,8.0,4.0,6.0,3.0,5.0,7.0,5.0,1.0,2.0,4.0,6.0,8.0,4.0,6.0,3.0,5.0,7.0,5.0,1.0,3.0,3.0,3.0,3.0,6.0,6.0,8.0,8.0,8.0,11.0,1.0,3.0,3.0,3.0,3.0,6.0,6.0,8.0,8.0,8.0,11.0,42231.0,678384.0,95220.0,638592.0,413155.0,45780.0,171229.0,67333.0,119839.0,143790.0,195215.0,462944.0,563066.0,8800.0,67304.0,158253.0,133126.0,186524.0,93223.0,121115.0,232110.0,289732.0,None,None,None,None,None,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25975,25976,24558,24558,2015/2016,9,2015-09-23 00:00:00,1992092,9824,10199,1,2,1.0,3.0,5.0,7.0,2.0,4.0,6.0,8.0,5.0,4.0,6.0,1.0,2.0,4.0,6.0,8.0,3.0,5.0,7.0,3.0,5.0,7.0,1.0,3.0,3.0,3.0,7.0,7.0,7.0,7.0,9.0,11.0,11.0,1.0,3.0,3.0,3.0,3.0,7.0,7.0,7.0,10.0,10.0,10.0,33272.0,41621.0,25813.0,257845.0,114735.0,42237.0,113227.0,358156.0,32343.0,531309.0,37257.0,42276.0,114792.0,150007.0,178119.0,27232.0,570830.0,260708.0,201704.0,36382.0,34082.0,95257.0,None,None,None,None,None,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25976,25977,24558,24558,2015/2016,9,2015-09-23 00:00:00,1992093,9956,10179,2,0,1.0,2.0,4.0,6.0,8.0,4.0,6.0,3.0,5.0,7.0,5.0,1.0,2.0,4.0,6.0,8.0,4.0,6.0,3.0,5.0,7.0,5.0,1.0,3.0,3.0,3.0,3.0,6.0,6.0,8.0,8.0,8.0,11.0,1.0,3.0,3.0,3.0,3.0,6.0,6.0,8.0,8.0,8.0,11.0,157856.0,274779.0,177689.0,294256.0,42258.0,39979.0,173936.0,147959.0,451983.0,80564.0,289472.0,10637.0,67349.0,202663.0,32597.0,114794.0,188114.0,25840.0,482200.0,95230.0,451335.0,275122.0,None,None,None,None,None,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25977,25978,24558,24558,2015/2016,9,2015-09-22 00:00:00,1992094,7896,10243,0,0,1.0,2.0,4.0,6.0,8.0,3.0,7.0,5.0,3.0,5.0,7.0,1.0,2.0,4.0,6.0,8.0,4.0,6.0,3.0,5.0,7.0,5.0,1.0,3.0,3.0,3.0,3.0,7.0,7.0,7.0,10.0,10.0,10.0,1.0,3.0,3.0,3.0,3.0,6.0,6.0,8.0,8.0,8.0,11.0,NaN,8881.0,173534.0,39646.0,282287.0,340790.0,393337.0,8893.0,614454.0,93229.0,178142.0,274776.0,121080.0,197757.0,260964.0,231614.0,113235.0,41116.0,462608.0,42262.0,92252.0,194532.0,None,None,None,None,None,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25978,25979,24558,24558,2015/2016,9,2015-09-23 00:00:00,1992095,10192,9931,4,3,1.0,2.0,4.0,6.0,8.0,2.0,4.0,6.0,8.0,4.0,6.0,1.0,2.0,4.0,6.0,8.0,4.0,6.0,3.0,5.0,7.0,5.0,1.0,3.0,3.0,3.0,3.0,7.0,7.0,7.0,7.0,10.0,10.0,1.0,3.0,3.0,3.0,3.0,6.0,6.0,8.0,8.0,8.0,11.0,274787.0,492132.0,108451.0,25815.0,94553.0,384376.0,598355.0,36785.0,45174.0,302079.0,71764.0,156175.0,95216.0,172768.0,22834.0,458806.0,207234.0,25772.0,40274.0,34035.0,41726.0,527103.0,None,None,None,None,None,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [72]:
def Stats(df, t_id, season):
    #selecteer de club
    wedstrijd = df[((df['home_team_api_id'] == t_id) | (df['away_team_api_id'] == t_id)) & (df['season'] == season)]
    
    #bepaal het aantal wedstrijden dat de club heeft gespeeld
    
    
    #bereken het aantal punten behaald en het gemiddelde aantal punten per seizoen.
    aantal_wedstrijden = len(wedstrijd)
    punten = 0
    for index, wedstrijden in wedstrijd.iterrows():
        if wedstrijden['home_team_api_id'] == t_id:
            if wedstrijden['home_team_goal'] > wedstrijden['away_team_goal']:
                punten += 3
            elif wedstrijden['home_team_goal'] == wedstrijden['away_team_goal']:
                punten += 1
        else:
            if wedstrijden['away_team_goal'] > wedstrijden['home_team_goal']:
                punten += 3
            elif wedstrijden['away_team_goal'] == wedstrijden['home_team_goal']:
                punten += 1
    gemiddeld_punten_per_wedstrijd = punten / aantal_wedstrijden
    
    thuis = wedstrijd[wedstrijd['home_team_api_id'] == t_id]
    uit = wedstrijd[wedstrijd['away_team_api_id'] == t_id]

    
    aantal_thuiswedstrijden = len(thuis)
    aantal_uitwedstrijden = len(uit)

    gewonnen_thuis = len(thuis[thuis['home_team_goal'] > thuis['away_team_goal']])
    verloren_thuis = len(thuis[thuis['home_team_goal'] < thuis['away_team_goal']])
    gelijk_thuis = len(thuis[thuis['home_team_goal'] == thuis['away_team_goal']])

    gewonnen_uit = len(uit[uit['away_team_goal'] > uit['home_team_goal']])
    verloren_uit = len(uit[uit['away_team_goal'] < uit['home_team_goal']])
    gelijk_uit = len(uit[uit['away_team_goal'] == uit['home_team_goal']])

    # Bereken het winst-, verlies- en gelijk percentage voor thuis- en uitwedstrijden
    winst_perc_thuis = gewonnen_thuis / aantal_thuiswedstrijden * 100
    verlies_perc_thuis = verloren_thuis / aantal_thuiswedstrijden * 100
    gelijk_perc_thuis = gelijk_thuis / aantal_thuiswedstrijden * 100

    winst_perc_uit = gewonnen_uit / aantal_uitwedstrijden * 100
    verlies_perc_uit = verloren_uit / aantal_uitwedstrijden * 100
    gelijk_perc_uit = gelijk_uit / aantal_uitwedstrijden * 100
    
    resultaten = {'team id': t_id,
                  'gemiddeld punten': gemiddeld_punten_per_wedstrijd, 
                  'totaal punten':punten, 
                  'winst thuis in %': winst_perc_thuis,
                  'winst uit in %': winst_perc_uit,
                  'verlies thuis in %': verlies_perc_thuis, 
                  'verlies uit in %': verlies_perc_uit, 
                  'gelijk thuis in %': gelijk_perc_thuis, 
                  'gelijk uit in %': gelijk_perc_uit}
    return resultaten, wedstrijd

In [73]:
resultaten, wedstrijd= Stats(Match, 8640, '2008/2009')
display(resultaten)

{'team id': 8640,
 'gemiddeld punten': 1.911764705882353,
 'totaal punten': 65,
 'winst thuis': 64.70588235294117,
 'winst uit': 47.05882352941176,
 'verlies thuis': 11.76470588235294,
 'verlies uit': 29.411764705882355,
 'gelijk thuis': 23.52941176470588,
 'gelijk uit': 23.52941176470588}

def rangenlijst(season1):
    season = '2008/2009'
    for i in Match[season1]():
        if df[i].is_unique:
            Stats(Match, i , season)

rangenlijst('2008/2009')

In [ ]:
team_naam = df[df['team_api_id'] == team_id]['team_name'].values[0]

In [94]:
def Ranglijst(df, season):
    # Maak een lege dictionary aan om de punten per team bij te houden
    punten_per_team = {}

    # Loop over alle wedstrijden van het seizoen
    for index, wedstrijd in df[df['season'] == season].iterrows():
        home_team = wedstrijd['home_team_api_id']
        away_team = wedstrijd['away_team_api_id']
        resultaten_home, _ = Stats(df, home_team, season)
        resultaten_away, _ = Stats(df, away_team, season)

        # Voeg de behaalde punten van de thuis- en uitploeg toe aan de dictionary
        if home_team in punten_per_team:
            punten_per_team[home_team] += resultaten_home['totaal punten']
        else:
            punten_per_team[home_team] = resultaten_home['totaal punten']

        if away_team in punten_per_team:
            punten_per_team[away_team] += resultaten_away['totaal punten']
        else:
            punten_per_team[away_team] = resultaten_away['totaal punten']

    # Sorteer de dictionary op basis van de behaalde punten
    sorted_punten = sorted(punten_per_team.items(), key=lambda x: x[1], reverse=True)

    # Print de ranglijst
    print("Ranglijst seizoen " + season + ":")
    for i, (team_id, punten) in enumerate(sorted_punten):
        team_naam = df[df['home_team_api_id'] == team_id]['home_team_api_id'].values[0]
        print(str(i+1) + ". " + team_naam + " (" + str(punten) + " punten)")

In [93]:
print(Match.columns)

Index(['id', 'country_id', 'league_id', 'season', 'stage', 'date',
       'match_api_id', 'home_team_api_id', 'away_team_api_id',
       'home_team_goal',
       ...
       'SJA', 'VCH', 'VCD', 'VCA', 'GBH', 'GBD', 'GBA', 'BSH', 'BSD', 'BSA'],
      dtype='object', length=115)

In [ ]:
Ranglijst(Match, '2008/2009')